In [0]:
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql import functions as f
from pyspark.sql.functions import lower, col
import requests

spark = SparkSession.builder.getOrCreate()

In [0]:
#Read json file directly from s3 bucket
df = spark.read.json("s3a://csparkdata/ol_cdump.json")

In [0]:
df.count()

Out[3]: 148163

In [0]:
df.printSchema()

root
 |-- alternate_names: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- authors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- author: struct (nullable = true)
 |    |    |    |-- key: string (nullable = true)
 |    |    |-- key: string (nullable = true)
 |    |    |-- type: string (nullable = true)
 |-- bio: string (nullable = true)
 |-- birth_date: string (nullable = true)
 |-- by_statement: string (nullable = true)
 |-- contributions: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- contributors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- name: string (nullable = true)
 |    |    |-- role: string (nullable = true)
 |-- copyright_date: string (nullable = true)
 |-- covers: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- created: struct (nullable = true)
 |    |-- type: string (nullable = true)
 |    |-- value: string (nullable = true)
 |-- death_date: string (nullable = true)
 |-- description: string (nullable = true)
 |-- dewey_decimal_class: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- dewey_number: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- download_url: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- edition_name: string (nullable = true)
 |-- excerpts: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- excerpt: struct (nullable = true)
 |    |    |    |-- type: string (nullable = true)
 |    |    |    |-- value: string (nullable = true)
 |    |    |-- page: string (nullable = true)
 |-- first_publish_date: string (nullable = true)
 |-- first_sentence: string (nullable = true)
 |-- full_title: string (nullable = true)
 |-- fuller_name: string (nullable = true)
 |-- genres: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- ia_box_id: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- ia_loaded_id: string (nullable = true)
 |-- identifiers: struct (nullable = true)
 |    |-- amazon: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- amazon.co.uk_asin: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- goodreads: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- librarything: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |-- isbn_10: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- isbn_13: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- isbn_invalid: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- isbn_odd_length: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- key: string (nullable = true)
 |-- languages: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- key: string (nullable = true)
 |-- last_modified: struct (nullable = true)
 |    |-- type: string (nullable = true)
 |    |-- value: string (nullable = true)
 |-- latest_revision: long (nullable = true)
 |-- lc_classifications: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- lccn: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- links: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- title: string (nullable = true)
 |    |    |-- type: struct (nullable = true)
 |    |    |    |-- key: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |-- location: string (nullable = true)
 |-- name: string (nullable = true)
 |-- notes: string (nullable = true)
 |-- number_of_pages: long (nullable = true)
 |-- ocaid: string (nullable = true)
 |-- oclc_number: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- oclc_numbers: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- other_titles: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- pagination: string (nullable = true)
 |-- personal_name: string (nullable = true)
 |-- photos: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- physical_dimensions: string (nullable = true)
 |-- physical_format: string (nullable = true)
 |-- publish_country: string (nullable = true)
 |-- publish_date: string (nullable = true)
 |-- publish_places: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- publishers: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- purchase_url: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- revision: long (nullable = true)
 |-- series: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- source_records: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subject_people: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subject_place: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subject_places: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subject_time: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subject_times: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subjects: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subtitle: string (nullable = true)
 |-- table_of_contents: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- class: string (nullable = true)
 |    |    |-- label: string (nullable = true)
 |    |    |-- level: long (nullable = true)
 |    |    |-- pagenum: string (nullable = true)
 |    |    |-- title: string (nullable = true)
 |    |    |-- type: string (nullable = true)
 |    |    |-- value: string (nullable = true)
 |-- title: string (nullable = true)
 |-- title_prefix: string (nullable = true)
 |-- type: struct (nullable = true)
 |    |-- key: string (nullable = true)
 |-- uri_descriptions: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- uris: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- url: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- website: string (nullable = true)
 |-- weight: string (nullable = true)
 |-- work_title: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- work_titles: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- works: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- key: string (nullable = true)

In [0]:
df.createOrReplaceTempView("rawData")

#### Data Profiling and Data Explortion

In [0]:
#Viewing data accross all columns
pd.set_option("display.max_columns", None)
spark.sql('''select * from rawData limit 100''').toPandas()

/databricks/spark/python/pyspark/sql/pandas/conversion.py:92: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Unable to convert the field authors. If this column is not necessary, you may consider dropping it or converting to primitive type before the conversion.
Direct cause: Unsupported type in conversion to Arrow: ArrayType(StructType(List(StructField(author,StructType(List(StructField(key,StringType,true))),true),StructField(key,StringType,true),StructField(type,StringType,true))),true)
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warnings.warn(msg)

,alternate_names,authors,bio,birth_date,by_statement,contributions,contributors,copyright_date,covers,created,death_date,description,dewey_decimal_class,dewey_number,download_url,edition_name,excerpts,first_publish_date,first_sentence,full_title,fuller_name,genres,ia_box_id,ia_loaded_id,identifiers,isbn_10,isbn_13,isbn_invalid,isbn_odd_length,key,languages,last_modified,latest_revision,lc_classifications,lccn,links,location,name,notes,number_of_pages,ocaid,oclc_number,oclc_numbers,other_titles,pagination,personal_name,photos,physical_dimensions,physical_format,publish_country,publish_date,publish_places,publishers,purchase_url,revision,series,source_records,subject_people,subject_place,subject_places,subject_time,subject_times,subjects,subtitle,table_of_contents,title,title_prefix,type,uri_descriptions,uris,url,website,weight,work_title,work_titles,works
0,None,"[(None, /authors/OL6535896A, None)]",None,None,by Lillian Rose Arnold,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:13.854568)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783906M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Microfilm of typ...",161.0,None,[3954579],None,"[Marking tools, Motivational treatment]","xi, 161 leaves",None,None,None,None,gau,1975,[Athens],[University of Georgia],None,2,None,None,None,None,None,None,None,"[Creative thinking -- Testing, Educational psy...",None,None,The effect of differentiated marking tools and...,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681062W,)]"
1,None,"[(None, /authors/OL6535897A, None)]",None,None,by Walter Edward Stead,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:14.436633)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783907M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Vita\n\nMicrofil...",164.0,None,[3954635],None,None,"ix, 164 leaves :",None,None,None,None,lau,1976,[Baton Rouge],[Louisiana State University],None,2,None,None,None,None,None,None,None,"[Problem solving, Group problem solving, Socia...",a field study,None,Comparison of the nominal grouping and sequenc...,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681063W,)]"
2,None,"[(None, /authors/OL6535898A, None)]",None,None,by Raymond L. Kuhlman,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:16.147537)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783908M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Includes index\n...",262.0,None,[3955196],None,None,"vi, 262 p. :",None,None,None,None,gau,1977,"[Loganville, Ga]",[Institute Press],None,2,None,None,None,None,None,None,None,"[Industrial accidents -- Investigation, Indust...",investigative methods and techniques,None,Professional accident investigation,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681064W,)]"
3,None,"[(None, /authors/OL5900510A, None)]",None,None,a cura di Sergio Rossi,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:25.050320)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783909M,"[(/languages/ita,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Commentary and n...",310.0,None,[3957350],None,None,310 p. ;,None,None,None,None,it,1964,[Napoli],[Edizioni Scientifiche Italiane],None,2,"[Collana di letterature moderne ; 20, Collana ...",None,None,None,None,None,None,"[English poetry -- Scottish authors, Scottish ...",None,None,I chauceriani scozzesi,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL12983281W,)]"
4,None,"[(None, /authors/OL135548A, None)]",None,None,Francesco de Sanctis ; a cura di Sergio Romagnoli,"[Romagnoli, Sergio]",None,None,None,"(/type/datetime, 2008-12-30T07:38:27.016116)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783911M,"[(/languages/ita,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,None,145.0,None,[3957370],None,None,145 p. ;,None,None,None,None,it,1955,[Padova],[Liviana Editrice],None,2,"[Collana di testi e documenti, Collana di test...",None,None,None,None,None,None,"[Petrarca, Francesco, -- 1304-1374]",e altri scritti,None,Lezioni zurighesi sul Petrarca,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL1330425W,)]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,None,"[(None, /authors/OL6535931A, None)]",None,None,Arnold E. Bender,None,None,None,None,"(/type/datetime, 2008-12-30T07:45:41.734927)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[0120864509],None,None,None,/books/OL22784009M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,[77075370],None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Includes index\n...",243.0,None,[3988934],None,None,243 p. :,None,None,None,None,enk,1978,"[London, New York]",[Academic Press],None,2,"[Food science and technology, Food science and...",None,None,None,None,None,None,"[Food industry and trade, Food -- Preservation...",None,None,Food processing and nutrition,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681098W,)]"
96,None,"[(None, /authors/OL1662297A, None)]",None,None,E. Nicola Siri ; ilustraciones de Holden,None,None,None,None,"(/type/datetime, 2008-12-30T07:45:46.782622)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22784011M,"[(/languages/spa,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Bibliographical ...",156.0,None,[3989837],None,None,156 p. ;,None,None,None,None,ag,1940,[Buenos Aires],[Editorial Atlántida],None,2,"[Biblioteca Billiken ; Colección azúl, Bibliot...",None,None,None,None,None,None,"[Bouchard, Hipólito, -- 1785-1843]",None,None,"Buchardo, ""el halcón de los mares""",None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL6350015W,)]"
97,None,"[(None, /authors/OL6535932A, None)]",None,None,Lauzinho Cuque ; desenhos de A. Poloni (sob or...,"[Poloni, A]",None,None,None,"(/type/datetime, 2008-12-30T07:45:48.463779)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22784012M,"[(/languages/por,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,None,62.0,None,[3989882],None,None,62 leaves :,None,None,None,None,xx,1970,[[s.n],[s.l.],None,2,None,None,None,None,None,None,None,"[Creative ability, Problem solving]",None,None,A simplicidade dos processos criativos,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681099W,)]"
98,None,"[(None, /authors/OL4282497A, None)]",None,None,traduction et notes par Stanciu Stoian et Ode ...,"[Stoian, Stanciu, Chateauvieux Lebel, Ode de]",None,None,None,"(/type/datetime, 2008-12-30T07:45:52.765058)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22784013M,"[(/languages/fre,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",3,None,[32014722],None,"[""NBuC""]",None,None,245.0,None,[3990637],None,None,"5 p. l., [iii]-xvii, 245 p., 3 l.",None,None,None,None,xx,1931,[Paris],[Maisonneuve frères],None,3,[Les littératures jpopulaires de toutes les na...,[marc:wfm_bk_marc/wfm_bk_marc:89234423:1130],None,None,None,None,None,None,None,"[(None, None, None, None, Contes merveilleux.,...",Contes populaires de Roumanie <Pove.sti>,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL10347245W,)]"
99,None,"[(None, /authors/OL128956A, None)]",None,None,con un saggio di Carlo Bassi; testo e didascal...,"[Bassi, Carlo]",None,None,None,"(/type/datetime, 2008-12-30T07:45:54.351380)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22784014M,"[(/languages/ita,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Text in Italian ...",544.0,None,[3990836],None,[Museums - architecture - technics],"xxx, 544 p.",None,None,None,None,xx,1962,[Milano],[U. Hoepli],None,2,[His Esempi di architettura e decorazioni d'og...,None,None,None,None,None,None,[Museums],architettura - tecnica,None,Musei,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL1274724W,)]"

In [0]:
#Fetching distinct authors value present in column authors
spark.sql('''select distinct authors from rawData''').toPandas()

/databricks/spark/python/pyspark/sql/pandas/conversion.py:92: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Unable to convert the field authors. If this column is not necessary, you may consider dropping it or converting to primitive type before the conversion.
Direct cause: Unsupported type in conversion to Arrow: ArrayType(StructType(List(StructField(author,StructType(List(StructField(key,StringType,true))),true),StructField(key,StringType,true),StructField(type,StringType,true))),true)
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warnings.warn(msg)

,authors
0,"[(None, /authors/OL4670954A, None)]"
1,"[(None, /authors/OL6536041A, None)]"
2,"[(None, /authors/OL6536108A, None)]"
3,"[(None, /authors/OL6286129A, None)]"
4,"[(None, /authors/OL6536450A, None)]"
...,...
104843,"[(None, /authors/OL1429695A, None)]"
104844,"[(None, /authors/OL6570515A, None)]"
104845,"[(None, /authors/OL4914295A, None)]"
104846,"[(None, /authors/OL1810291A, None)]"
104847,"[((/authors/OL5291959A,), None, {""key"":""/type/..."

In [0]:
#Fetching distinct authors value present in column authors with complete full length
df_authors = spark.sql('''
  select distinct authors from rawData
  order by length(cast(authors as string)) desc
''')

In [0]:
pd.set_option("display.max_colwidth", None)
df_authors.toPandas()

/databricks/spark/python/pyspark/sql/pandas/conversion.py:92: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Unable to convert the field authors. If this column is not necessary, you may consider dropping it or converting to primitive type before the conversion.
Direct cause: Unsupported type in conversion to Arrow: ArrayType(StructType(List(StructField(author,StructType(List(StructField(key,StringType,true))),true),StructField(key,StringType,true),StructField(type,StringType,true))),true)
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warnings.warn(msg)

,authors
0,"[((/authors/OL7123935A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123936A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123937A,), None, {""key"":""/type/author_role""}), ((/authors/OL184825A,), None, {""key"":""/type/author_role""}), ((/authors/OL60090A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123938A,), None, {""key"":""/type/author_role""}), ((/authors/OL4062539A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123939A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123940A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123941A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123942A,), None, {""key"":""/type/author_role""}), ((/authors/OL6522430A,), None, {""key"":""/type/author_role""}), ((/authors/OL339531A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123943A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123944A,), None, {""key"":""/type/author_role""}), ((/authors/OL1494319A,), None, {""key"":""/type/author_role""}), ((/authors/OL91329A,), None, {""key"":""/type/author_role""}), ((/authors/OL436461A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123945A,), None, {""key"":""/type/author_role""}), ((/authors/OL1528966A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123946A,), None, {""key"":""/type/author_role""})]"
1,"[((/authors/OL7123935A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123936A,), None, {""key"":""/type/author_role""}), ((/authors/OL260363A,), None, {""key"":""/type/author_role""}), ((/authors/OL184825A,), None, {""key"":""/type/author_role""}), ((/authors/OL60090A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123938A,), None, {""key"":""/type/author_role""}), ((/authors/OL4062539A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123939A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123940A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123941A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123942A,), None, {""key"":""/type/author_role""}), ((/authors/OL6522430A,), None, {""key"":""/type/author_role""}), ((/authors/OL339531A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123943A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123944A,), None, {""key"":""/type/author_role""}), ((/authors/OL1494319A,), None, {""key"":""/type/author_role""}), ((/authors/OL91329A,), None, {""key"":""/type/author_role""}), ((/authors/OL436461A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123945A,), None, {""key"":""/type/author_role""}), ((/authors/OL1528966A,), None, {""key"":""/type/author_role""}), ((/authors/OL7123948A,), None, {""key"":""/type/author_role""})]"
2,"[(None, /authors/OL3426340A, None), (None, /authors/OL2570377A, None), (None, /authors/OL538066A, None), (None, /authors/OL3426341A, None), (None, /authors/OL2711555A, None), (None, /authors/OL3426342A, None), (None, /authors/OL3426343A, None), (None, /authors/OL3426344A, None), (None, /authors/OL3426345A, None)]"
3,"[((/authors/OL7127527A,), None, {""key"":""/type/author_role""}), ((/authors/OL7127528A,), None, {""key"":""/type/author_role""}), ((/authors/OL7127529A,), None, {""key"":""/type/author_role""}), ((/authors/OL7127530A,), None, {""key"":""/type/author_role""})]"
4,"[(None, /authors/OL4521280A, None), (None, /authors/OL5988230A, None), (None, /authors/OL6075042A, None), (None, /authors/OL5986396A, None), (None, /authors/OL5987708A, None), (None, /authors/OL5986397A, None)]"
...,...
104843,"[(None, /authors/OL98590A, None)]"
104844,"[(None, /authors/OL54121A, None)]"
104845,"[(None, /authors/OL7030A, None)]"
104846,"[(None, /authors/OL2886A, None)]"
104847,None

In [0]:
df_authors.createOrReplaceTempView('df_authors')

In [0]:
#Fetching the maximum size of list present in author column
max_author_count = spark.sql('''
select max(size(authors)) as author_count from df_authors where authors is not null
''').toPandas()["author_count"][0]

In [0]:
max_author_count

Out[12]: 21

In [0]:
#As data in author column is inconsistent creating two new columns as leadAuthor,co_authors with assumption the first tuple in each list is leadAuthor and rest of them are co_authors
df_authors_final = spark.sql(f'''select *, authors[0] as leadAuthor, slice(authors, 2, {max_author_count - 1}) as co_authors from rawData where authors is not null''')

In [0]:
pd.set_option("display.max_colwidth", None)
df_authors_final.toPandas()

/databricks/spark/python/pyspark/sql/pandas/conversion.py:92: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Unable to convert the field authors. If this column is not necessary, you may consider dropping it or converting to primitive type before the conversion.
Direct cause: Unsupported type in conversion to Arrow: ArrayType(StructType(List(StructField(author,StructType(List(StructField(key,StringType,true))),true),StructField(key,StringType,true),StructField(type,StringType,true))),true)
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warnings.warn(msg)

,alternate_names,authors,bio,birth_date,by_statement,contributions,contributors,copyright_date,covers,created,death_date,description,dewey_decimal_class,dewey_number,download_url,edition_name,excerpts,first_publish_date,first_sentence,full_title,fuller_name,genres,ia_box_id,ia_loaded_id,identifiers,isbn_10,isbn_13,isbn_invalid,isbn_odd_length,key,languages,last_modified,latest_revision,lc_classifications,lccn,links,location,name,notes,number_of_pages,ocaid,oclc_number,oclc_numbers,other_titles,pagination,personal_name,photos,physical_dimensions,physical_format,publish_country,publish_date,publish_places,publishers,purchase_url,revision,series,source_records,subject_people,subject_place,subject_places,subject_time,subject_times,subjects,subtitle,table_of_contents,title,title_prefix,type,uri_descriptions,uris,url,website,weight,work_title,work_titles,works,leadAuthor,co_authors
0,None,"[(None, /authors/OL6535896A, None)]",None,None,by Lillian Rose Arnold,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:13.854568)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783906M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Microfilm of typescript. Ann Arbor, Mich. : University Microfilms, 1975. -- 1 reel ; 35 mm\n\nThesis--University of Georgia\n\nBibliography: leaves 147-161""}",161.0,None,[3954579],None,"[Marking tools, Motivational treatment]","xi, 161 leaves",None,None,None,None,gau,1975,[Athens],[University of Georgia],None,2,None,None,None,None,None,None,None,"[Creative thinking -- Testing, Educational psychology]",None,None,The effect of differentiated marking tools and motivational treatment on figural creativity,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681062W,)]","(None, /authors/OL6535896A, None)",[]
1,None,"[(None, /authors/OL6535897A, None)]",None,None,by Walter Edward Stead,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:14.436633)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783907M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Vita\n\nMicrofilm of typescript. Ann Arbor, Mich. : University Microfilms, 1976. -- 1 reel ; 35 mm\n\nThesis--Louisiana State University\n\nBibliography: leaves 124-128""}",164.0,None,[3954635],None,None,"ix, 164 leaves :",None,None,None,None,lau,1976,[Baton Rouge],[Louisiana State University],None,2,None,None,None,None,None,None,None,"[Problem solving, Group problem solving, Social groups]",a field study,None,Comparison of the nominal grouping and sequenced brainstorming techniques of creative idea generation,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681063W,)]","(None, /authors/OL6535897A, None)",[]
2,None,"[(None, /authors/OL6535898A, None)]",None,None,by Raymond L. Kuhlman,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:16.147537)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783908M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Includes index\n\nLoose-leaf\n\nCover title\n\nBibliography : p. 146-147""}",262.0,None,[3955196],None,None,"vi, 262 p. :",None,None,None,None,gau,1977,"[Loganville, Ga]",[Institute Press],None,2,None,None,None,None,None,None,None,"[Industrial accidents -- Investigation, Industrial safety]",investigative methods and techniques,None,Professional accident investigation,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13681064W,)]","(None, /authors/OL6535898A, None)",[]
3,None,"[(None, /authors/OL5900510A, None)]",None,None,a cura di Sergio Rossi,None,None,None,None,"(/type/datetime, 2008-12-30T07:38:25.050320)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783909M,"[(/languages/ita,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,"{""type"":""/type/text"",""value"":""Commentary and notes in Italian; poetry in Middle English""}",310.0,None,[3957350],None,None,310 p. ;,None,None,None,None,it,1964,[Napoli],[Edizioni Scientifiche Italiane],None,2,"[Collana di letterature moderne ; 20, Collana di letterature moderne -- 20]",None,None,None,None,None,None,"[English poetry -- Scottish authors, Scottish poetry -- History and criticism, Scottish poetry -- To 1700]",None,None,I chauceriani scozzesi,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL12983281W,)]","(None, /authors/OL5900510A, None)",[]
4,None,"[(None, /authors/OL135548A, None)]",None,None,Francesco de Sanctis ; a cura di Sergio Romagnoli,"[Romagnoli, Sergio]",None,None,None,"(/type/datetime, 2008-12-30T07:38:27.016116)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22783911M,"[(/languages/ita,)]","(/type/datetime, 2009-12-15T08:04:07.512219)",2,None,None,None,"[""NBuC""]",None,None,145.0,None,[3957370],None,None,145 p. ;,None,None,None,None,it,1955,[Padova],[Liviana Editrice],None,2,"[Collana di testi e documenti, Collana di testi e documenti]",None,None,None,None,None,None,"[Petrarca, Francesco, -- 1304-1374]",e altri scritti,None,Lezioni zurighesi sul Petrarca,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL1330425W,)]","(None, /authors/OL135548A, None)",[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145617,None,"[(None, /authors/OL6570936A, None)]",None,None,Parviz Qazi Said.,None,None,None,None,"(/type/datetime, 2009-02-17T21:41:21.255066)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22992915M,"[(/languages/per,)]","(/type/datetime, 2009-12-15T08:15:36.817467)",2,None,None,None,None,None,"{""type"":""/type/text"",""value"":""Mystery novel.\n\nIn Persian.""}",221.0,None,None,None,None,221 p. ;,None,None,None,None,ir,2003,[Tihrān],[Musassihsih yi Asia],None,2,None,None,None,None,None,None,None,None,None,None,Duzakhi-ha,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13724799W,)]","(None, /authors/OL6570936A, None)",[]
145618,None,"[(None, /authors/OL6559855A, None)]",None,None,prepared and submitted by Esherick Homsey Dodge and Davis.,None,None,None,None,"(/type/datetime, 2009-02-17T21:41:21.476846)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22992916M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:15:36.817467)",3,None,None,None,None,None,None,68.0,None,None,[60208979],"[Plan for the San Francisco Zoological Gardens, Plan for the San Francisco Zoo :]",[68] p. :,None,None,None,None,cau,1976,[San Francisco],[Esherick Homsey Dodge and Davis],None,3,None,[marc:SanFranPL13/SanFranPL13.out:1522815:1187],None,None,None,None,None,"[San Francisco Zoo (San Francisco, Calif.), Zoos -- California -- San Francisco, Recreational surveys -- California -- San Francisco]",a plan for the San Francisco Zoological Gardens,None,Visitor survey,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13708034W,)]","(None, /authors/OL6559855A, None)",[]
145619,None,"[(None, /authors/OL6570936A, None)]",None,None,Parviz Qazi Said.,None,None,None,None,"(/type/datetime, 2009-02-17T21:41:22.485046)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,/books/OL22992917M,"[(/languages/per,)]","(/type/datetime, 2009-12-15T08:15:36.817467)",2,None,None,None,None,None,"{""type"":""/type/text"",""value"":""Mystery novel.\n\nIn Persian.""}",445.0,None,None,None,None,445 p. ;,None,None,None,None,ir,2001,[Tihrān],[Musassihsih yi Asia],None,2,None,None,None,None,None,None,None,None,None,None,Lavsun dar ashiyanih yi marg,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13724800W,)]","(None, /authors/OL6570936A, None)",[]
145620,None,"[(None, /authors/OL333892A, None)]",None,None,written and illustrated by Evelyn Lip.,None,None,None,None,"(/type/datetime, 2009-02-17T21:41:23.349426)",None,None,None,None,None,3rd ed.,None,None,None,None,None,None,None,None,None,[9971947110],None,None,None,/books/OL22992920M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:15:36.817467)",2,None,None,None,None,None,None,104.0,None,None,None,None,104 p. :,None,None,None,None,si,1987,[Singapore],[Graham Brash],None,2,None,None,None,None,None,None,None,[Horoscopes.],None,None,Fun with Chinese horoscopes,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL2422992W,)]","(None, /authors/OL333892A, None)",[]
145621,None,"[(None, /authors/OL6570937A, None)]",None,None,"Mari J. Henson, Dan O. Henson.","[Henson, Dan O.]",None,None,None,"(/type/datetime, 2009-02-17T21:41:24.132118)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,[9718832564],None,None,None,/books/OL22992921M,"[(/languages/eng,)]","(/type/datetime, 2009-12-15T08:15:36.817467)",3,None,None,None,None,None,None,64.0,None,None,[55112519],None,64 p. :,None,None,None,None,ph,2001,"[Quezon City, [Philippines]]",[Giraffe Books],None,3,None,[marc:SanFranPL12/SanFranPL12.out:17104850:815],None,None,None,None,None,[Games -- Philippines],None,None,Games Filipino children used to play,None,"(/type/edition,)",None,None,None,None,None,None,None,"[(/works/OL13724804W,)]","(None, /authors/OL6570937A, None)",[]

In [0]:
df_authors_final.createOrReplaceTempView('df_authors_final')

In [0]:
spark.sql('''select distinct created from rawData''').toPandas()

,created
0,"{'type': '/type/datetime', 'value': '2008-12-30T07:54:22.727333'}"
1,"{'type': '/type/datetime', 'value': '2008-12-30T08:02:52.074120'}"
2,"{'type': '/type/datetime', 'value': '2008-12-30T08:08:06.099456'}"
3,"{'type': '/type/datetime', 'value': '2008-12-30T08:14:49.099540'}"
4,"{'type': '/type/datetime', 'value': '2008-12-30T08:27:18.947609'}"
...,...
143284,"{'type': '/type/datetime', 'value': '2009-02-17T21:32:56.620426'}"
143285,"{'type': '/type/datetime', 'value': '2009-02-17T21:34:51.008596'}"
143286,"{'type': '/type/datetime', 'value': '2009-02-17T21:35:10.996716'}"
143287,"{'type': '/type/datetime', 'value': '2009-02-17T21:40:24.426668'}"
143288,"{'type': '/type/datetime', 'value': '2009-02-17T21:41:20.883481'}"

In [0]:
spark.sql('''select distinct publish_date from rawData''').toPandas()

,publish_date
0,"October 25, 2005"
1,September 1994
2,3606
3,"July 23, 2005"
4,August 2003
...,...
1722,"March 15, 2007"
1723,September 1980
1724,"July 3, 2006"
1725,"February 3, 2000"
1726,"August 7, 2007"

In [0]:
spark.sql('''select distinct title from rawData''').toPandas()

,title
0,Crisis
1,Prhyme ribs
2,A study of the effectiveness of selected creative exercises on creative thinking and the mastery of a unit in elementary science
3,Verbal and imaginal processes in learning
4,DOVE IN THE WINDOW
...,...
134124,"Transfer matrix, green function and related techniques"
134125,Íslenzk-ensk orðabók
134126,Workforce training resource guide
134127,Marte y Venus hacen las paces
134128,"Edward Hopper, 1882-1967"

In [0]:
spark.sql('''select distinct name from rawData''').toPandas()

,name
0,d사아이디◑((스카이프dkdlel9876))▦네이버아이디판매
1,Eugene P. Tramm
2,"Paul ""The Miracle Man"" Liegeois"
3,Earlene Fowler
4,Deborah J. Ellis
...,...
327,BRAZIL. INSTITUTO DE PLANEJAMENTO ECONOMICO E SOCIAL. INSTITUTO DE PESQUISAS
328,Resource Centre for Multi-racial education.
329,G. L. Rabenhorst
330,United States. Congress. Joint Committee on Internal Revenue Taxation.
331,United States. Congress. Senate. Committee on Foreign Relations. Subcommittee on Senate Resolution 50.

In [0]:
spark.sql('''select distinct genres name from rawData''').toPandas()

,name
0,"[Biography, Personal narratives, German]"
1,"[Registers., Biography., Genealogy.]"
2,[Personal narratives]
3,[Controversial literature]
4,[music.]
...,...
1592,"[Personal narratives, Hungarian.]"
1593,"[ Fiction., Ficción.]"
1594,[Syntax.]
1595,"[Fiction., Poetry.]"
1596,"[Biography., Miscelanea., Miscellanea.]"

In [0]:
#Exploding Genres to check the differnces,repeating instances
spark.sql('''
  select explode(genres), count(*) from rawData group by 1 order by 2 desc
''').toPandas()

,col,count(1)
0,Fiction.,3934
1,Biography.,2778
2,Juvenile literature.,1783
3,Exhibitions.,1052
4,Guidebooks.,587
...,...,...
2989,Fiction.,1
2990,Ficción.,1
2991,Syntax.,1
2992,Fiction.,1
2993,Poetry.,1

In [0]:
spark.sql('''select distinct(explode(genres)) from rawData''').toPandas()

,col
0,Art collections
1,Personal narratives
2,Controversial literature
3,music.
4,Folklore
...,...
742,Inglaterra.
743,"Humor, Pictorial."
744,Caicatures and cartoons.
745,Translations from Japanese.
746,Syntax.

In [0]:
#Checking for conditions to standardise genres : Replacing the '.' from end of the string
df_explode_genres = spark.sql('''select *, explode(genres) as genre from df_authors_final''')

df_genres1 = df_explode_genres.withColumn("genre", f.regexp_replace(f.col("genre"), "\.$", ""))
df_genres1.createOrReplaceTempView('df_genres1')
spark.sql('''select count(distinct genre) from df_genres1''').toPandas()

,count(DISTINCT genre)
0,606

In [0]:
#Checking for conditions to standardise genres : Replacing the '.' from end of the string and converting all in lower case
df_genres2 = df_explode_genres.withColumn("genre", lower(f.regexp_replace(f.col("genre"), "\.$", "")))
df_genres2.createOrReplaceTempView('df_genres2')
spark.sql('''select count(distinct genre) from df_genres2''').toPandas()

,count(DISTINCT genre)
0,588

In [0]:
spark.sql('''select distinct key from rawData''').toPandas()

,key
0,/books/OL22784124M
1,/books/OL22784197M
2,/books/OL22784979M
3,/books/OL22785172M
4,/books/OL22785254M
...,...
147696,/books/OL22992159M
147697,/books/OL22992220M
147698,/books/OL22992555M
147699,/books/OL22992618M
147700,/books/OL22992701M

#### Null Check on key columns

In [0]:
#Null check for all the important columns
spark.sql('''select count(case when authors is null then 1 end) as authorsNullCount,
    count(case when created is null then 1 end) as createdNullCount,
    count(case when first_publish_date is null then 1 end) as first_publish_dateNullCount,
    count(case when genres is null then 1 end) as genresNullCount,
    count(case when name is null then 1 end) as nameNullCount,
    count(case when number_of_pages is null then 1 end) as number_of_pagesNullCount,
    count(case when publish_date is null then 1 end) as publish_dateNullCount,
    count(case when title is null then 1 end) as titleNullCount,
    count(case when key is null then 1 end) as keyNullCount,
    count(case when ocaid is null then 1 end) as ocaidNullCount
from rawData''').toPandas()

,authorsNullCount,createdNullCount,first_publish_dateNullCount,genresNullCount,nameNullCount,number_of_pagesNullCount,publish_dateNullCount,titleNullCount,keyNullCount,ocaidNullCount
0,2541,2163,147458,123369,147824,33072,9935,1311,0,125794

#### Standardisation of Publish date

In [0]:
spark.conf.set("spark.sql.legacy.timeParserPolicy", "LEGACY")

In [0]:
#Converting all the date formats present in column publish_date to the standard format
df_publishDate_final = df_authors_final.withColumn("publish_date_updated", f.expr('''
case
    when to_date(publish_date, "dd MMM yyyy") is not null then to_date(publish_date, "dd MMM yyyy")
    when to_date(publish_date, "dd/MM/yyyy") is not null then to_date(publish_date, "dd/MM/yyyy")
    when to_date(publish_date, "MM/dd/yyyy") is not null then to_date(publish_date, "MM/dd/yyyy")
    when to_date(publish_date, "MM-dd-yyyy") is not null then to_date(publish_date, "MM-dd-yyyy")
    when to_date(publish_date, "MM.dd.yyyy") is not null then to_date(publish_date, "MM.dd.yyyy")
    when to_date(publish_date, "MM/dd/yy") is not null then to_date(publish_date, "MM/dd/yy")
    when to_date(publish_date, "MM-dd-yy") is not null then to_date(publish_date, "MM-dd-yy")
    when to_date(publish_date, "MM/yyyy") is not null then to_date(publish_date, "MM/yyyy")
    when to_date(publish_date, "MMMM d, yyyy") is not null then to_date(publish_date, "MMMM d, yyyy")
    when to_date(publish_date, "MMMM d,yy") is not null then to_date(publish_date, "MMMM d,yy")
    when to_date(publish_date, "MMMM yyyy") is not null then to_date(publish_date, "MMMM yyyy")
    when to_date(publish_date, "MMMM, yyyy") is not null then to_date(publish_date, "MMMM, yyyy")
    when to_date(publish_date, "yyyy") is not null then to_date(publish_date, "yyyy")
    else null
end
'''))

In [0]:
df_publishDate_final.createOrReplaceTempView('df_publishDate_final')

In [0]:
spark.sql('''select distinct publish_date_updated from df_publishDate_final''').show()

+--------------------+
|publish_date_updated|
+--------------------+
|          1975-01-01|
|          1963-01-01|
|          1976-01-01|
|                null|
|          1969-01-01|
|          1874-01-01|
|          1957-01-01|
|          1953-01-01|
|          1965-01-01|
|          1968-01-01|
|          1962-01-01|
|          1960-01-01|
|          1955-01-01|
|          1964-01-01|
|          1966-01-01|
|          1978-01-01|
|          1961-01-01|
|          1917-01-01|
|          1977-01-01|
|          1983-01-01|
+--------------------+
only showing top 20 rows

#### Fetch Publish Year

In [0]:
#Fetching Publish Year from standarsised publish date column
df_publish_year = spark.sql('''
  select *,
  case 
    when publish_date_updated is not null then year(publish_date_updated) 
    else null
  end as publish_year
  from df_publishDate_final
''')

In [0]:
df_publish_year.createOrReplaceTempView("df_publish_year")

In [0]:
spark.sql('''select distinct publish_year from df_publish_year''').show()

+------------+
|publish_year|
+------------+
|        1975|
|        1977|
|        1955|
|        1978|
|        1961|
|        null|
|        1968|
|        1917|
|        1874|
|        1966|
|        1969|
|        1957|
|        1963|
|        1965|
|        1960|
|        1970|
|        1953|
|        1983|
|        1964|
|        1976|
+------------+
only showing top 20 rows

#### Clean Up Of data

In [0]:
#CleanUp of data
clean_data_df = spark.sql('''
  select * from df_publish_year 
  where number_of_pages > 20
  and publish_year >= 1950
  and publish_date_updated is not null
  and key is not null
  and authors is not null
  and title is not null
''')

In [0]:
clean_data_df.createOrReplaceTempView('clean_data_df')

In [0]:
clean_data_df.count()

Out[36]: 77823

#### Get the book with the most pages

In [0]:
point4_query1 = spark.sql('''
  select distinct key as book_key, title as book_title, number_of_pages from
  (select *, dense_rank() over (order by number_of_pages desc) as dnk_rnk from clean_data_df)
  where dnk_rnk = 1
''').toPandas()

In [0]:
point4_query1

,book_key,book_title,number_of_pages
0,/books/OL22855337M,Nihon shokuminchi kenchikuron,48418

#### Find the top 5 genres with most books

In [0]:
#Using same logic as tried in data profiling to standardise the genre column values and adding them in another column
df_explode_genres = spark.sql('''select *, explode(genres) as genre from clean_data_df''')

df_genres = df_explode_genres.withColumn("genre", lower(f.regexp_replace(f.col("genre"), "\.$", "")))

df_genres.createOrReplaceTempView("df_genres")

#select book with most pages using dense_rank function
point4_query2 = spark.sql('''
  select * from (
  select rank() over (order by books desc) as genre_rank, genre, books from
  (select genre, count(distinct key) as books from df_genres group by 1)
  ) where genre_rank <=5
  order by genre_rank
''').toPandas()

In [0]:
point4_query2

,genre_rank,genre,books
0,1,fiction,3418
1,2,biography,2747
2,3,juvenile literature,1677
3,4,exhibitions,1150
4,5,juvenile fiction,694

In [0]:
#Exploding Co-authors values to get data at each co-author level
point4_query3_co_author = spark.sql('''select *, explode(co_authors) as author_key from clean_data_df''')

In [0]:
point4_query3_co_author.createOrReplaceTempView("point4_query3_co_author")

#### Retrieve the top 5 authors who (co-)authored the most books.

In [0]:
point4_query3 = spark.sql('''
  select author_rank, author_key, books from (
  select *, rank() over (order by books desc) as author_rank from
  (select author_key, count(distinct key) as books from point4_query3_co_author group by 1)
  )
  where author_rank <= 5
  order by author_rank
''').toPandas()

/databricks/spark/python/pyspark/sql/pandas/conversion.py:92: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Unable to convert the field author_key. If this column is not necessary, you may consider dropping it or converting to primitive type before the conversion.
Direct cause: Nested StructType not supported in conversion to Arrow
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warnings.warn(msg)

In [0]:
point4_query3

,author_rank,author_key,books
0,1,"(None, /authors/OL3246797A, None)",45
1,2,"(None, /authors/OL2756622A, None)",13
2,3,"(None, /authors/OL1901196A, None)",11
3,4,"(None, /authors/OL1660476A, None)",10
4,5,"(None, /authors/OL2838553A, None)",7

#### Per publish year, get the number of authors that published at least one book.

In [0]:
#Explode the authors column to aggregate data for each author
point4_query4_explode_authors = spark.sql('''select *, explode(authors) as author_key from clean_data_df''')

In [0]:
point4_query4_explode_authors.createOrReplaceTempView('point4_query4_explode_authors')

point4_query4 = spark.sql('''select publish_year, count(distinct author_key) as authors from
  (select *, author_key from point4_query4_explode_authors)
  group by 1
  order by 1
''').toPandas()

In [0]:
pd.set_option("display.max_rows", None)
point4_query4

,publish_year,authors
0,1950,614
1,1951,648
2,1952,601
3,1953,601
4,1954,645
5,1955,589
6,1956,638
7,1957,706
8,1958,755
9,1959,830
10,1960,924
11,1961,1027
12,1962,1066
13,1963,1099
14,1964,1196
15,1965,1251
16,1966,1204
17,1967,1244
18,1968,1088
19,1969,1211
20,1970,1142
21,1971,1073
22,1972,1021
23,1973,1140
24,1974,1105
25,1975,990
26,1976,893
27,1977,712
28,1978,748
29,1979,825
30,1980,868
31,1981,838
32,1982,937
33,1983,984
34,1984,1025
35,1985,1021
36,1986,1098
37,1987,1170
38,1988,1247
39,1989,1409
40,1990,1630
41,1991,1590
42,1992,1795
43,1993,1858
44,1994,2137
45,1995,2357
46,1996,1934
47,1997,2212
48,1998,2020
49,1999,1334
50,2000,1069
51,2001,853
52,2002,1006
53,2003,1307
54,2004,1207
55,2005,1288
56,2006,1310
57,2007,2360
58,2008,3827
59,2009,172
60,2010,4
61,2011,1
62,2972,1
63,3606,1
64,3707,1
65,5703,1
66,5704,1
67,8727,1
68,9971,1
69,9999,3

#### Find the number of authors and number of books published per month for years between 1950 and 1970.

In [0]:
point4_query5 = spark.sql('''
  select date_format(publish_date_updated, "yyyy-MM") as publish_year_month, count(distinct author_key) as authors, count(distinct key) as books from
  (select *, author_key from point4_query4_explode_authors)
  where publish_year >= 1950 and publish_year <= 1970
  group by 1
  order by 1
''').toPandas()

In [0]:
point4_query5

,publish_year_month,authors,books
0,1950-01,614,647
1,1951-01,648,676
2,1952-01,601,633
3,1953-01,600,622
4,1953-10,1,1
5,1954-01,644,666
6,1954-06,1,1
7,1955-01,588,611
8,1955-06,1,1
9,1956-01,638,664
10,1957-01,705,740
11,1957-09,1,1
12,1958-01,753,789
13,1958-06,2,1
14,1959-01,830,879
15,1960-01,922,963
16,1960-06,2,2
17,1961-01,1026,1074
18,1961-10,1,1
19,1962-01,1064,1128
20,1962-12,2,1
21,1963-01,1099,1182
22,1963-07,1,1
23,1964-01,1194,1268
24,1964-05,1,1
25,1964-06,1,1
26,1965-01,1248,1347
27,1965-06,3,1
28,1966-01,1203,1298
29,1966-11,1,1
30,1967-01,1243,1323
31,1967-06,1,1
32,1968-01,1082,1159
33,1968-05,1,1
34,1968-06,4,3
35,1968-07,1,1
36,1969-01,1210,1285
37,1969-06,2,1
38,1970-01,1139,1227
39,1970-06,3,2